# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import whoami_pb2 as whoami__pb2


class WhoamiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Whoami = channel.unary_unary(
                '/unibit.test.Whoami/Whoami',
                request_serializer=whoami__pb2.Request.SerializeToString,
                response_deserializer=whoami__pb2.Response.FromString,
                )


class WhoamiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Whoami(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WhoamiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Whoami': grpc.unary_unary_rpc_method_handler(
                    servicer.Whoami,
                    request_deserializer=whoami__pb2.Request.FromString,
                    response_serializer=whoami__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unibit.test.Whoami', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Whoami(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Whoami(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unibit.test.Whoami/Whoami',
            whoami__pb2.Request.SerializeToString,
            whoami__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
